version: '3'

services:

  proxy:
    image: nginx:1.19.0
    command: nginx-debug -g 'daemon off;'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 5001:80

  app:
    image: node:18-alpine
    command: /app/container-startup.sh
    volumes:
      - ./app:/app
